const consign = require('consign');

consign({cwd:'app'})
    .include('bootstrap/config.js')
    .then('util/log.js')
    .then('bootstrap/express.js')
    .then('util/validadorDeData.js')
    .then('util/customValidations.js')
    .then('util')
    .then('database')
    .then('modelo/licenca.js')
    .then('modelo')
    .then('repositorio')
    .then('servico')
    .then('middleware/corsInterceptor.js')
    .then('middleware/GenericTokenInterceptor.js')
    .then('middleware/apiTokenInterceptor.js')
    .then('middleware/webTokenInterceptor.js')
    .then('middleware/basicAuthInterceptor.js')
    .then('controlador')
    .then('rota/authRoutes.js')
    .then('rota')
    .then('middleware/errorInterceptor.js')
    .then('bootstrap/runner.js')
    .into({});
