mysql:
  frota:
    host: 172.18.107.248
    username: frota
    password: frota
    port: 3306
    database: frota_znh
  sso:
    host: 172.18.107.248
    username: frota
    password: frota
    port: 3306
    database: sso

mongodb:
    url: mongodb://172.18.107.204:27017/frota_znh

sso:
    url: http://172.18.107.240:3000

rjConsultores:
  url: http://34.198.151.111:9991
  authorization: Basic bTJtOnJqbTJtcmo=

worker-processamento:
  api: http://localhost:8080

worker-servico:
  api: http://localhost:8989

amqp:
    url: amqp://admin:admin@172.18.107.201
    servico-persistencia: lazypersistenceTesteDiego

jwt:
  api_key: M2MParceiroKey
  web_key: m2m

server:
  port: 3000

log:
  path: var/log
  maxSize: 100000
  maxFiles: 10
  files:
    erro: monitriip-erro.log
    info: monitriip-info.log
