mysql:
  frota:
    host: 172.18.107.248
    username: frota
    password: frota
    port: 3306
    database: frota_znh
  sso:
    host: 172.18.107.248
    username: frota
    password: frota
    port: 3306
    database: sso

mongodb:
    url: mongodb://172.18.107.204:27017/frota_znh

sso:
    url: http://172.18.107.240:3000

amqp:
    url: amqp://admin:admin@172.18.107.201
    servico-persistencia: lazypersistence
    worker-processamento:
      queue: eventos.monitriip
      exchange-dlq: processador.monitriip.DLQ
      routing-key-dql: dead.letters

cache:
  linha:
    seconds: 10
  motorista:
    seconds: 10
  veiculo:
    seconds: 10

server:
  port: 3005

log:
  path: var/log
  maxSize: 100000
  maxFiles: 10
  files:
    erro: monitriip-erro.log
    info: monitriip-info.log



